### ISSUE TITLE
LAB TEST 1

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-A201-GROUP-H/LAB-TEST#1]
### **INSTRUCTIONS**

[STIA1113 Lab Test 1.docx](https://github.com/STIA1113-A201-GROUP-H/LAB-TEST/files/5686026/STIA1113.Lab.Test.1.docx)

### **SUBMISSION**
1.	Submit the complete code and sample output for all of the questions.
2.	Submit your answers on GitHub.
3.	Due date: 14 DIS 2020 (11.20am)

### **Guideline Policy**
1.	A late penalty of 5% will be accessed for each hour that the assignment is past due. After the five-hour late period, an assignment will receive a grade of zero.
2.	Any program that does not show a reasonable attempt at completing the lab test will earn a grade of zero.
3.	Don't try to just find someone to do your test for you. 
4.	If you copy someone's work without his/her permission or if you let your friend copies your work, both of you are cheating and there will be an appropriate penalty.

**Comment by Dayat102** [comment]
Name: Muhammad Hidayat Bin Ibrahim
Matric Number: 279395

https://github.com/Dayat102/Lab-test.git

**Comment by zhiyi16510** [comment]
Name: Teoh Zhi Yi
Matric Number: 278645

https://github.com/zhiyi16510/LabTest1.git

**Comment by piqahamir** [comment]
Name : Nur Afiqah bt Mohd Amir
Matric Num : 278415

https://github.com/piqahamir/Lab-Test1.git

**Comment by ffangtn** [comment]
Name : Fanny Tang Tung Huong
Matric Number : 278366
https://github.com/ffangtn/Labtest-1/tree/master/Lab%20test1/src

**Comment by MohamadAmmar123** [comment]
Name : Mohamad Ammar Bin Azizan
Matric No : 278642
Java: https://github.com/MohamadAmmar123/STIA1113_A201/blob/master/src/LabTest/LabTest1.java
Output Q1 : https://github.com/MohamadAmmar123/STIA1113_A201/blob/master/src/LabTest/OutputL1Q1.png
Output Q2 : https://github.com/MohamadAmmar123/STIA1113_A201/blob/master/src/LabTest/OutputL1Q2.png

**Comment by LimKitEeNatelie** [comment]
Name: Lim Kit Ee,Natelie
Matric Number: 277649

https://github.com/LimKitEeNatelie/LabTest1.git

**Comment by ngchunlong279645** [comment]
Name : NG CHUN LONG
Matric Number : 279645
https://github.com/ngchunlong279645/LAB-TEST-1/tree/master/Labtest1/src/question

**Comment by lohsiewchin** [comment]
Name : LOH SIEW CHIN
Matric Number : 278723
https://github.com/kellyloh811/Lab-Test/tree/main/LabTest1/src

**Comment by FatinShamas** [comment]
Name: Nur Fatin Nasuha Binti Shamas
Matric Number: 278062

https://github.com/FatinShamas/LabTest1.git

**Comment by tehyeexin** [comment]
Name: TEH YEE XIN
Matric Number: 278070
https://github.com/tehyeexin/LAB_TEST-STIA1113/tree/master/src/LabTest1

**Comment by chunkhai8** [comment]
Name: Nah Chun Khai
Number Matric: 278798
https://github.com/chunkhai8/LABTEST1

**Comment by khooyenni** [comment]
Name: Khoo Yen Ni
Number Matric: 278520
https://github.com/khooyenni/LabTest.git

**Comment by ChunWai279321** [comment]
Name: Wong Chun Wai
No. Matric: 279321
https://github.com/ChunWai279321/Lab-Test/blob/master/Lab-Texts/src/LT1.java

**Comment by WoonZhunPing** [comment]
https://github.com/WoonZhunPing/LABTEST1.git

**Comment by WoonZhunPing** [comment]
Name : Woon Zhun Ping
No. Matric : 279144
https://github.com/WoonZhunPing/LABTEST1.git

**Comment by adamamir** [comment]
Name: Mohd Adam bin Amir
Matric No.: 277705
https://github.com/adamamir/LaabTest.git

**Comment by leetzongying** [comment]
Lee Tzong Ying (279093)

https://github.com/leetzongying/labtest1/tree/master/LabTest1

**Comment by SNaqilah** [comment]
SITI NUR AQILAH (277795)

https://github.com/SNaqilah/LabTest.git

**Comment by NajibahAtiqah** [comment]
import java.util.Scanner;

public class TestLAB1 {
//QUESTION2
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner in=new Scanner(System.in);

		System.out.print("Pls enter your sales: ");
		double Sales1=in.nextDouble();
		System.out.print("Enter the hours worked: ");
		double Hours1=in.nextDouble();
		System.out.println();

		double com1=Sales1*0.05;
		double com2=Sales1*0.10;
		double com3=Sales1*0.15;
		double Hourlywages=Hours1*5;
		double dailywages1=Hourlywages+com1;
		double dailywages2=Hourlywages+com2;
		double dailywages3=Hourlywages+com3;

		if (Sales1>=50 && Sales1 <=300) {
			System.out.println("Your commission is: " + "RM" + com1);
		} else if(Sales1 >= 301 && Sales1 <= 500) {
			System.out.println("Your commission is: " + "RM" + com2);
		} else if(Sales1 > 500) {
			System.out.println("Your commission is: " + "RM" + com3);
		}

		if (Sales1 >= 50 && Sales1 <= 300) {
			System.out.println("Your daily wages is: " + "RM" + dailywages1);
		} else if(Sales1 >= 301 && Sales1 <= 500) {
			System.out.println("Your daily wages is: " + "RM" + dailywages2);
		} else if(Sales1 > 500) {
			System.out.println("Your daily wages is: " + "RM" + dailywages3);
		}
	}

{
		
		
		
	}

{

	}

}

**Comment by ChongCheeTwau278751** [comment]
https://github.com/ChongCheeTwau278751/LabTest

**Comment by JasonLau278177** [comment]
Name: Jason Lau
No. Matric: 278177
https://github.com/JasonLau278177/LabTest

**Comment by qingyunleong** [comment]
Name: Leong Qing Yun
No. Matric: 277585

https://github.com/qingyunleong/LABTest1

**Comment by Saifuddin-s277838** [comment]
Name : Ahmad Saifuddin bin Ilias
No. Matric : 277838

https://github.com/Saifuddin-s277838/githubeclipse/blob/master/GitHubStuff/src/githubprojects/LabTest1question1.java 
https://github.com/Saifuddin-s277838/githubeclipse/blob/master/GitHubStuff/src/githubprojects/LabTest1question2.java

repository got problem so I created new one

**Comment by shakir277980** [comment]
https://github.com/shakir277980/labtest

**Comment by Chong-LeeTing** [comment]
Name: Chong Lee Ting
Matric no: 278455
https://github.com/Chong-LeeTing/labtest1.git

**Comment by Farahanim-nym** [comment]
https://github.com/Farahanim-nym/LabTest1

**Comment by Ainurnatasya17** [comment]
AINUR NATASYA BT MOHAMAD RAIS
277638
https://github.com/Ainurnatasya17/LabTest1.git

**Comment by YongBoonKeat** [comment]
Name: YONG BOON KEAT 
No matric: 278722
https://github.com/YongBoonKeat/LabTest1

**Comment by izannuddin** [comment]
https://github.com/izannuddin/labtest

**Comment by Pee278802** [comment]
Name: Pee Foo Ye
No Matric: 278802
https://github.com/Pee278802/Labtest

**Comment by athirahbazilah** [comment]
https://github.com/athirahbazilah/LabTest1.git

**Comment by Nurafiza058** [comment]
Nurafiza Binti Abdul Rashid
277839
https://github.com/Nurafiza058/ExcerciseProg1/tree/main/Labtest1

**Comment by jiakee1026** [comment]
Name: TAN JIA KEE
No Matric: 279437
https://github.com/jiakee1026/Lab-Test-1.git

**Comment by puteriwan** [comment]
Name: Puteri Wan Norshahzreena binti Surani
Matric No: 277617
https://github.com/puteriwan/LabTest/tree/master/QuizS/src

**Comment by NGZIHENG** [comment]
Name: NG ZI HENG
Matric No: 278024
https://github.com/NGZIHENG/labtest1-278024-.git

**Comment by shakir277980** [comment]
https://github.com/shakir277980/labtest2

**Comment by nurqurratuaini** [comment]
https://github.com/nurqurratuaini/exercises/tree/main/Test

**Comment by izannuddin** [comment]
https://github.com/izannuddin/labtest0/tree/master/labtest0/src/labtest0

**Comment by izannuddin** [comment]
https://github.com/izannuddin/labtest2

**Comment by NajibahAtiqah** [comment]
import java.util.Scanner;
public class TestLAB1 {
//QUESTION1
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner in=new Scanner(System.in);

		int Items;
		int Price1, Price2, Price3 ;
		int Quant1, Quant2, Quant3;
		double Tot1, Tot2, Tot3, TotPrice, Discount ;
		
		System.out.println ("Pls enter the number of items : ");
		Items = in.nextInt () ;
		System.out.print ("Pls enter the price of first items : RM ");
		Price1 = in.nextInt () ;
		System.out.print("Pls enter the quantity of first items : ");
		Quant1 = in.nextInt () ;
		System.out.println () ;
		
		Tot1 = Price1 * Quant1;
		
		System.out.println ("Pls enter the price of second items : RM ");
		Price2 = in.nextInt () ;
		System.out.print("Pls enter the quantity of second items : ");
		Quant2 = in.nextInt () ;
		System.out.println () ;
		
		Tot2 = Price2 * Quant2;
		
		System.out.println ("Pls enter the price of third items : RM ");
		Price3 = in.nextInt () ;
		System.out.print("Pls enter the quantity of third items : ");
		Quant3 = in.nextInt () ;
		System.out.println () ;
		
		Tot3 = Price3 * Quant3;
				
		TotPrice = Tot1 + Tot2 + Tot3;
		System.out.println ("Total price : RM " + TotPrice);
		
		if (TotPrice > 100)
			Discount = (TotPrice * 0.2);
		else
			Discount = (TotPrice * 0.1);
		
		System.out.println ("DisCount received is: RM " + Discount);
		System.out.println ("Price to be paid is: RM " + (TotPrice - Discount));
		System.out.println("Thankyouu for your purchase at C_Marts Shopping Complex. Have a good day :) !");
		

		
		
	}

}
